apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-demo
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
      - name: hello-demo
        image: hello-demo:1.0   # local image inside minikube
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-demo-service
spec:
  type: NodePort
  selector:
    app: hello-demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081   # free port

